### ISSUE TITLE
DatePicker Fehler

### ISSUE THREAD

**Issue by ChibyKito** [dh060296/Gruppe_6_Restaurant_Tischreservierung#5]
Methode Fehlerhaft, falscher Wert erhalte
![Fehlermeldung](https://user-images.githubusercontent.com/85340820/150597626-340029b8-4373-41bb-b241-e974d9fd87ab.JPG)
n

**Comment by dh060296** [comment]
DatePicker is fixed now

**Comment by dh060296** [comment]
fixed with Issue #3  together

**Comment by dh060296** [comment]
@dschuler-halberg
